onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {TB: top_redpitaya_125_14_tb ALL signals}
add wave -noupdate /top_redpitaya_125_14_tb/ctrl_sim_ended
add wave -noupdate /top_redpitaya_125_14_tb/i
add wave -noupdate /top_redpitaya_125_14_tb/in_adc_clk_p
add wave -noupdate /top_redpitaya_125_14_tb/in_adc_clk_n
add wave -noupdate /top_redpitaya_125_14_tb/in_data_ch1
add wave -noupdate /top_redpitaya_125_14_tb/in_data_ch2
add wave -noupdate /top_redpitaya_125_14_tb/dac_o_data
add wave -noupdate /top_redpitaya_125_14_tb/dac_o_iqsel
add wave -noupdate /top_redpitaya_125_14_tb/dac_o_iqclk
add wave -noupdate /top_redpitaya_125_14_tb/dac_o_iqwrt
add wave -noupdate /top_redpitaya_125_14_tb/dac_o_iqrst
add wave -noupdate /top_redpitaya_125_14_tb/adc_i_clkstb
add wave -noupdate /top_redpitaya_125_14_tb/leds
add wave -noupdate /top_redpitaya_125_14_tb/aclk
add wave -noupdate /top_redpitaya_125_14_tb/o_multiacc_o_acc_valid_i
add wave -noupdate /top_redpitaya_125_14_tb/o_fifo_data_ch1
add wave -noupdate /top_redpitaya_125_14_tb/o_fifo_data_ch2
add wave -noupdate /top_redpitaya_125_14_tb/o_fifo_data_ch1_valid
add wave -noupdate /top_redpitaya_125_14_tb/o_fifo_data_ch2_valid
add wave -noupdate /top_redpitaya_125_14_tb/i_fifo_rd_dready_ch1
add wave -noupdate /top_redpitaya_125_14_tb/i_fifo_rd_dready_ch2
add wave -noupdate /top_redpitaya_125_14_tb/i_cmddata_axi_fifo_i_data
add wave -noupdate /top_redpitaya_125_14_tb/i_cmddata_axi_fifo_i_valid
add wave -noupdate /top_redpitaya_125_14_tb/o_cmddata_axi_fifo_o_ready
add wave -noupdate /top_redpitaya_125_14_tb/i_cmd_axi_fifo_i_data
add wave -noupdate /top_redpitaya_125_14_tb/i_cmd_axi_fifo_i_valid
add wave -noupdate /top_redpitaya_125_14_tb/o_cmd_axi_fifo_o_ready
add wave -noupdate /top_redpitaya_125_14_tb/o_multichrdctrl_cmd_dready_i
add wave -noupdate /top_redpitaya_125_14_tb/o_multichrdctrl_cmd_dready_q
add wave -noupdate /top_redpitaya_125_14_tb/i_acc_trigger_1
add wave -noupdate /top_redpitaya_125_14_tb/i_acc_trigger_2
add wave -noupdate /top_redpitaya_125_14_tb/clk_iq
add wave -noupdate /top_redpitaya_125_14_tb/cos_value
add wave -noupdate /top_redpitaya_125_14_tb/sin_value
add wave -noupdate /top_redpitaya_125_14_tb/iq_value
add wave -noupdate /top_redpitaya_125_14_tb/iq_increment
add wave -noupdate -divider {DUT: 'top_redpitaya_125_14' IN ports}
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/in_adc_clk_n
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/in_data_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/i_fifo_rd_dready_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/i_fifo_rd_dready_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/in_adc_clk_p
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/i_cmd_axi_fifo_i_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/i_cmd_axi_fifo_i_data
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/i_cmddata_axi_fifo_i_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/i_acc_trigger_1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/i_acc_trigger_2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/aclk
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/in_data_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/i_cmddata_axi_fifo_i_data
add wave -noupdate -divider {DUT: 'top_redpitaya_125_14' OUT ports}
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/o_fifo_data_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/o_fifo_data_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/leds
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_o_iqclk
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/o_multichrdctrl_cmd_dready_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/o_cmddata_axi_fifo_o_ready
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_i_clkstb
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_o_iqsel
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_o_iqwrt
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/o_fifo_data_ch1_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/o_fifo_data_ch2_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_o_data
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/o_cmd_axi_fifo_o_ready
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_o_iqrst
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/o_multichrdctrl_cmd_dready_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/o_multiacc_o_acc_valid_i
add wave -noupdate -divider {DUT: 'top_redpitaya_125_14' INTERNAL signals}
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/rxcmd_pipeline_write_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multichrdctrl_cmd_dready_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_i_data_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_i_rd_en_channels_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_i_data_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_acc_valid_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/cmd_axi_fifo_o_data_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_empty_next_channels_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_i_rd_en_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_empty_channels_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/data_q_dsp_fifowidth
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_i_rd_en_channels_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/cmd_axi_fifo_o_data
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_empty_next_channels_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/cmddata_axi_fifo_o_data_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_i_rd_en_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_o_data_valid_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_rd_data_channels_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_empty_channels_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_o_data_valid_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dsp_o_data_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_i_rst
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_rd_data_channels_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_o_ready
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_i_data_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_o_rd_data_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_i_data_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_full_channels_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dsp_o_data_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_o_valid_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/cmd_axi_fifo_i_dready
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_o_valid_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/locked_mmcm1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/rxcmd_pipeline_addr
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_o_rd_data_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_i_channel_rd_select_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_clk_buf
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_full_channels_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multichrdctrl_o_single_wr_valid_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_rd_valid_channels_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multichrdctrl_o_single_wr_data_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/cmddata_axi_fifo_i_dready
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_o_channel_rd_select_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_i_dready_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_i_dready_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_i_channel_rd_select_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_o_fill_count_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/rxcmd_pipeline_cmd
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multichrdctrl_o_single_wr_valid_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_ready_channels_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_rd_valid_channels_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multichrdctrl_o_single_wr_data_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_o_channel_rd_select_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_iqclk_mmcm
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_o_fill_count_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_clk_mmcm
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/acc_trigger_1_synchronized
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/acc_trigger_2_synchronized
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/acc_trigger_1_synchronized_posedge
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/acc_trigger_2_synchronized_posedge
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/data_q_dsp_fifowidth_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_ready_channels_q
add wave -noupdate -radix decimal /top_redpitaya_125_14_tb/inst_dut/cmddata_axi_fifo_o_data
add wave -noupdate -radix unsigned /top_redpitaya_125_14_tb/inst_dut/multiacc_o_fill_count_channels_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/data_i_dsp_fifowidth_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_o_data_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_i_valid_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/fifo_wr_ready_ch1
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_o_rd_valid_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/adc_o_data_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_i_valid_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_full_next_channels_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/rxcmd_pipeline_data
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/fifo_wr_ready_ch2
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multichrdctrl_cmd_dready_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dsp_o_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/rxcmd_pipeline_read_valid
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_acc_valid_i
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/dac_iqwrt_mmcm
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_fill_count_channels_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/data_i_dsp_fifowidth
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/memrdsel_o_rd_valid_q
add wave -noupdate /top_redpitaya_125_14_tb/inst_dut/multiacc_o_full_next_channels_q
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {16078640 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 411
configure wave -valuecolwidth 253
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {22341488 ps}
