onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -divider {TB: top_redpitaya_daq_tb ALL signals}
add wave -noupdate /top_redpitaya_daq_tb/ctrl_sim_ended
add wave -noupdate /top_redpitaya_daq_tb/i
add wave -noupdate /top_redpitaya_daq_tb/in_adc_clk
add wave -noupdate /top_redpitaya_daq_tb/in_data_ch1
add wave -noupdate /top_redpitaya_daq_tb/in_data_ch2
add wave -noupdate /top_redpitaya_daq_tb/dac_o_data
add wave -noupdate /top_redpitaya_daq_tb/dac_o_iqsel
add wave -noupdate /top_redpitaya_daq_tb/dac_o_iqclk
add wave -noupdate /top_redpitaya_daq_tb/dac_o_iqwrt
add wave -noupdate /top_redpitaya_daq_tb/dac_o_iqrst
add wave -noupdate /top_redpitaya_daq_tb/adc_i_clkstb
add wave -noupdate /top_redpitaya_daq_tb/leds
add wave -noupdate /top_redpitaya_daq_tb/aclk
add wave -noupdate /top_redpitaya_daq_tb/o_multiacc_o_acc_valid_i
add wave -noupdate /top_redpitaya_daq_tb/o_fifo_data_ch1
add wave -noupdate /top_redpitaya_daq_tb/o_fifo_data_ch2
add wave -noupdate /top_redpitaya_daq_tb/o_fifo_data_ch1_valid
add wave -noupdate /top_redpitaya_daq_tb/o_fifo_data_ch2_valid
add wave -noupdate /top_redpitaya_daq_tb/i_fifo_rd_dready_ch1
add wave -noupdate /top_redpitaya_daq_tb/i_fifo_rd_dready_ch2
add wave -noupdate /top_redpitaya_daq_tb/i_cmddata_axi_fifo_i_data
add wave -noupdate /top_redpitaya_daq_tb/i_cmddata_axi_fifo_i_valid
add wave -noupdate /top_redpitaya_daq_tb/o_cmddata_axi_fifo_o_ready
add wave -noupdate /top_redpitaya_daq_tb/i_cmd_axi_fifo_i_data
add wave -noupdate /top_redpitaya_daq_tb/i_cmd_axi_fifo_i_valid
add wave -noupdate /top_redpitaya_daq_tb/o_cmd_axi_fifo_o_ready
add wave -noupdate /top_redpitaya_daq_tb/o_multichrdctrl_cmd_dready_i
add wave -noupdate /top_redpitaya_daq_tb/o_multichrdctrl_cmd_dready_q
add wave -noupdate /top_redpitaya_daq_tb/i_acc_trigger_1
add wave -noupdate /top_redpitaya_daq_tb/i_acc_trigger_2
add wave -noupdate /top_redpitaya_daq_tb/clk_iq
add wave -noupdate /top_redpitaya_daq_tb/cos_value
add wave -noupdate /top_redpitaya_daq_tb/sin_value
add wave -noupdate /top_redpitaya_daq_tb/iq_value
add wave -noupdate /top_redpitaya_daq_tb/iq_increment
add wave -noupdate /top_redpitaya_daq_tb/f_idata_ch1
add wave -noupdate /top_redpitaya_daq_tb/fitem_idata_ch1
add wave -noupdate /top_redpitaya_daq_tb/f_idata_ch2
add wave -noupdate /top_redpitaya_daq_tb/fitem_idata_ch2
add wave -noupdate -divider {DUT: 'top_redpitaya_daq' IN ports}
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/i_acc_trigger_1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/aclk
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/in_data_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/i_cmddata_axi_fifo_i_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/i_acc_trigger_2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/in_data_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/i_fifo_rd_dready_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/i_fifo_rd_dready_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/i_cmd_axi_fifo_i_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/i_cmd_axi_fifo_i_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/in_adc_clk
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/i_cmddata_axi_fifo_i_valid
add wave -noupdate -divider {DUT: 'top_redpitaya_daq' OUT ports}
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/o_multichrdctrl_cmd_dready_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/o_multiacc_o_acc_valid_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/o_fifo_data_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/o_fifo_data_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/leds
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_o_iqclk
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/o_multichrdctrl_cmd_dready_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/o_cmddata_axi_fifo_o_ready
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_i_clkstb
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_o_iqsel
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_o_iqwrt
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/o_fifo_data_ch1_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/o_fifo_data_ch2_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_o_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/o_cmd_axi_fifo_o_ready
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_o_iqrst
add wave -noupdate -divider {DUT: 'top_redpitaya_daq' INTERNAL signals}
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_full_next_channels_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_i_rd_en_channels_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_empty_channels_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_fill_count_channels_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_i_data_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_i_rd_en_channels_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_i_data_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_full_channels_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/acc_trigger_2_synchronized_posedge
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_empty_channels_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_fill_count_channels_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/data_i_dsp_fifowidth
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_full_channels_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_rd_valid_channels_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_empty_next_channels_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_o_ready
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/acc_trigger_2_synchronized
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_clk_mmcm
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/data_q_dsp_fifowidth
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/fifo_wr_ready_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/fifo_wr_ready_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_rd_valid_channels_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_empty_next_channels_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_o_valid_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_o_valid_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_o_data_valid_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_o_data_valid_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_iqclk_mmcm
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_clk_bufg
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dsp_o_data_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/acc_trigger_1_synchronized_posedge
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/data_i_dsp_fifowidth_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_o_data_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_o_data_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_acc_valid_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dsp_o_data_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_iqwrt_mmcm
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_ready_channels_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/acc_trigger_1_synchronized
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_rd_data_channels_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/data_q_dsp_fifowidth_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_i_data_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_i_data_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_acc_valid_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_ready_channels_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_i_rst
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_rd_data_channels_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_i_valid_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_i_dready_ch1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/locked_mmcm
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dac_i_valid_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multiacc_o_full_next_channels_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/rxcmd_pipeline_read_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/rxcmd_pipeline_addr
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/rxcmd_pipeline_write_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/rxcmd_pipeline_cmd
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/rxcmd_pipeline_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/clk
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/rst
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/i_cmd_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/i_cmd_rdchsel
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/i_cmd_rdcnt
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/o_cmd_ready
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/o_multichannel_rd_en
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/i_multichannel_rd_select
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/o_multichannel_rd_select
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/i_multichannel_rd_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/i_multichannel_rd_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/o_singlechannel_wr_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/o_singlechannel_wr_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/i_singlechannel_wr_dready
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/wr_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/wr_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/multichannel_rd_en
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/doing_stuff
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/rd_delay_counter
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/rd_delay_counter_enable
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/rdchsel
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_multichrdctrl_buffer1/rdcnt
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_o_rd_valid_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_o_fill_count_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_i_rd_en_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_o_rd_data_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_o_channel_rd_select_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_i_channel_rd_select_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_o_rd_data_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_i_channel_rd_select_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_i_rd_en_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_o_channel_rd_select_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/memrdsel_o_rd_valid_q
add wave -noupdate -color {Dark Orchid} -radix decimal /top_redpitaya_daq_tb/inst_dut/memrdsel_o_fill_count_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multichrdctrl_o_single_wr_data_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multichrdctrl_o_single_wr_valid_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multichrdctrl_cmd_dready_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multichrdctrl_cmd_dready_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multichrdctrl_o_single_wr_data_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/multichrdctrl_o_single_wr_valid_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/adc_i_dready_ch2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/dsp_o_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/cmd_axi_fifo_i_dready
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/cmddata_axi_fifo_i_dready
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/cmddata_axi_fifo_o_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/cmd_axi_fifo_o_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/cmd_axi_fifo_o_data_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/cmddata_axi_fifo_o_data_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/clk
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/rst
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/i_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/i_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/i_fir_cmd_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/i_fir_cmd_coeffsel
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/i_fir_cmd_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/i_avg_cmd_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/i_avg_cmd_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/o_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/o_data_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/o_data_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/conn_data_i_ddc
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/conn_data_q_ddc
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/conn_valid_ddc
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/o_valid_i
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_dsp_path/o_valid_q
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/clk
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/i_rst
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/i_acc_trigger
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/i_data_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/i_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/o_acc_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/i_rd_en_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/o_rd_valid_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/o_rd_data_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/o_ready_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/o_empty_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/o_empty_next_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/o_full_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/o_full_next_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/o_fill_count_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/wr_channel_select
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/channel_rd_select
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/channel_rounds_cnt
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/rst_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/wr_data
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/wr_data_p1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/wr_data_p2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/wr_valid
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/wr_valid_p1
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/wr_valid_p2
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/wr_accumulate
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/wr_valid_checked
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/rd_en_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/rd_data_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/ready_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/empty_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/empty_next_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/full_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/full_next_channels
add wave -noupdate -radix decimal /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/fill_count_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/items_written_round
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/items_accumulated_channels
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/items_accumulated_channels_next
add wave -noupdate /top_redpitaya_daq_tb/inst_dut/inst_fifo_accumulator_i/acc_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {17468000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 504
configure wave -valuecolwidth 450
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {18389485 ps} {21298954 ps}
